In [1]:
import time
import os
import io

from random import seed
from random import randint

from argparse import ArgumentParser, Namespace
import yaml
from multiprocessing import cpu_count

import matplotlib.pyplot as plt

# default is to maximize the objectives
import time as time
import copy
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import math
from scipy.stats import norm

# example of a gaussian process surrogate function
from math import sin
from math import pi
import numpy as np
from numpy import arange
from numpy import asarray
from numpy.random import normal
from numpy.random import uniform
from numpy.random import random
from numpy import cov

from warnings import catch_warnings
from warnings import simplefilter


from autooed.utils.sampling import lhs
import random
#import xgboost as xgb
#from xgboost import XGBRegressor
#from xgboost import plot_tree
from sklearn import linear_model
from sklearn import ensemble
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.tree import export_graphviz
from sklearn import svm
from sklearn.neural_network import MLPRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import LeaveOneOut
from sklearn.metrics import mean_absolute_error
from sklearn.inspection import partial_dependence, plot_partial_dependence
from sklearn.decomposition import PCA
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier

from scipy.stats import pearsonr
from scipy import ndimage, misc
import pickle
import re
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import Descriptors
from chainer_chemistry.datasets.molnet import get_molnet_dataset
# the package is in the same directory
# get Today's date from python!
from datetime import datetime
from autooed.utils.sampling import lhs
from autooed.problem import build_problem
from autooed.mobo import build_algorithm
from autooed.utils.seed import set_seed
from autooed.utils.initialization import generate_random_initial_samples, load_provided_initial_samples
from autooed.utils.plot import plot_performance_space, plot_performance_metric
from autooed.utils.plot import plot_performance_space_diffcolor
from argparse import ArgumentParser, Namespace
from arguments import get_args

/home/kianoosh/anaconda3/envs/rdkit_env/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/kianoosh/github/MOBO_RFcons_LCD3D_6monomers/autooed/mobo/surrogate_problem.py:36: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RF.fit(X_train, y_train)


1.0
0.875


In [2]:
# Change the default values for new argument
def get_general_args(args=None):
    '''
    General arguments: problem and algorithm description, experiment settings
    '''
    parser = ArgumentParser()

    parser.add_argument('--problem', type=str, default='printing3d_dlp', 
        help='optimization problem')
    parser.add_argument('--algo', type=str, default='tsemo',
        help='type of algorithm to use with some predefined arguments, or custom arguments')
    parser.add_argument('--seed', type=int, default=10,
        help='the specific seed to run')
    parser.add_argument('--batch-size', type=int, default=1, 
        help='size of the batch in optimization')
    parser.add_argument('--n-init-sample', type=int, default=0, 
        help='number of initial design samples')
    parser.add_argument('--n-total-sample', type=int, default=60, 
        help='number of total design samples (budget)')

    args, _ = parser.parse_known_args(args)
    return args


def get_surroagte_args(args=None):
    '''
    Arguments for fitting the surrogate model
    '''
    parser = ArgumentParser()

    parser.add_argument('--surrogate', type=str, 
        choices=['gp', 'nn', 'bnn'], default='gp', 
        help='type of the surrogate model')

    args, _ = parser.parse_known_args(args)
    return args


def get_acquisition_args(args=None):
    '''
    Arguments for acquisition function
    '''
    parser = ArgumentParser()

    parser.add_argument('--acquisition', type=str,  
        choices=['identity', 'pi', 'ei', 'ucb', 'ts'], default='ts', 
        help='type of the acquisition function')

    args, _ = parser.parse_known_args(args)
    return args


def get_solver_args(args=None):
    '''
    Arguments for multi-objective solver
    '''
    parser = ArgumentParser()

    # general solver
    parser.add_argument('--solver', type=str, 
        choices=['nsga2', 'moead', 'parego', 'discovery', 'ga', 'cmaes'], default='nsga2', 
        help='type of the multiobjective solver')
    parser.add_argument('--n-process', type=int, default=1,
        help='number of processes to be used for parallelization')

    args, _ = parser.parse_known_args(args)
    return args


def get_selection_args(args=None):
    '''
    Arguments for sample selection
    '''
    parser = ArgumentParser()

    parser.add_argument('--selection', type=str,
        choices=['direct', 'hvi', 'random', 'uncertainty'], default='hvi', 
        help='type of selection method for new batch')

    args, _ = parser.parse_known_args(args)
    return args

def get_args():
    '''
    Get arguments from all components
    You can specify args-path argument to directly load arguments from specified yaml file
    '''
    parser = ArgumentParser()
    parser.add_argument('--args-path', type=str, default=None,
        help='used for directly loading arguments from path of argument file')
    args, _ = parser.parse_known_args()

    if args.args_path is None:

        general_args = get_general_args()
        surroagte_args = get_surroagte_args()
        acquisition_args = get_acquisition_args()
        solver_args = get_solver_args()
        selection_args = get_selection_args()

        module_cfg = {
            'surrogate': vars(surroagte_args),
            'acquisition': vars(acquisition_args),
            'solver': vars(solver_args),
            'selection': vars(selection_args),
        }

    else:
        
        with open(args.args_path, 'r') as f:
            all_args = yaml.load(f)
        
        general_args = Namespace(**all_args['general'])
        module_cfg = all_args.copy()
        module_cfg.pop('general')

    return general_args, module_cfg

In [3]:
# printability as Y
df = pd.read_csv('Yuchao_20220511.csv')
#df = pd.read_csv('Imaginery_initial_.csv')
Printability = np.asarray (df['Printability']).reshape(1,-1)
Y0 = Printability.T
Y = np.where(Y0 == 'Y', 1, 0)


#X_ = df.to_numpy()
A_Ratio = np.asarray (df['R1(HA)']).reshape(1,-1)
B_Ratio = np.asarray (df['R2(IA)']).reshape(1,-1)
C_Ratio = np.asarray (df['R3(NVP)']).reshape(1,-1)
D_Ratio = np.asarray (df['R4(AA)']).reshape(1,-1)
E_Ratio = np.asarray (df['R5(HEAA)']).reshape(1,-1)
F_Ratio = np.asarray (df['R6(IBOA)']).reshape(1,-1)

# did not consider F_Ratio, since we do not have it in optimization
X_ = np.concatenate((A_Ratio.T, B_Ratio.T, C_Ratio.T, D_Ratio.T, E_Ratio.T), axis=1)


# load monomers descriptors
df = pd.read_csv('monomers_info.csv')
energy = np.array (-df['dft_sp_E_RB3LYP'])
pol_area = np.array (df['polar_surface_area'])
complexity = np.array (df['complexity'])
HA = np.array (df['HA'])

X0 = np.concatenate((A_Ratio.T, B_Ratio.T, C_Ratio.T, D_Ratio.T, E_Ratio.T, F_Ratio.T), axis=1)
X_energy = np.multiply (X0, energy)
#X_pol_area = np.multiply (X0, pol_area)
complexity = np.multiply (X0, complexity)
HA = np.multiply (X0, HA)

X = np.concatenate ((X_energy, complexity, HA), axis=1)

accuracy_test = []
accuracy_train = []
# got more information about input varialbe may reduce the accuracy for 
# few samples, but it is informative for new samples.

# ratio accuracy for 1000 repeat: 0.915875
# energy  + complexity + HA + Solubility accuracy for 1000 repeat: 0.912875
# energy  + complexity + Solubility accuracy for 1000 repeat: 0.908625 ! HA is important
# energy  + HA + Solubility accuracy for 1000 repeat: 0.90925 ! complexity is important
# Complexity + HA + Solubility accuracy for 1000 repeat: 0.91175 ! energy term not that important
# energy  + complexity + HA : 0.91175 ! Solubility is not that important 
# complexity + HA : 0.915375 So close to only ratios. 
# complexity : 0.910875
# Solubility: 0.90675
# HA: 0.91075 
# Solubility_h : 0.911125
# HA + Solubility_h: 0.915875 !! same as only ratio
# HA + Complexity + Solubility_h: 0.913
for i in range(0, 10):
    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=i)
    y_train = y_train.ravel()
    RF = RandomForestClassifier(max_depth=10, random_state=i)
    RF.fit(X_train, y_train)
    pred = RF.predict_proba(X_train)

    #print (RF.score(X_train, y_train))
    #print (RF.score(X_test, y_test))
    accuracy_test.append(RF.score(X_test, y_test))
    accuracy_train.append(RF.score(X_train, y_train))
print (np.mean (np.array (accuracy_train)))
print (np.mean (np.array (accuracy_test)))

1.0
0.9125


In [4]:
# load arguments
args, module_cfg = get_args()
print (args.seed)
# set random seed
set_seed(args.seed)

# build problem
problem = build_problem(args.problem)
print(problem)

# build algorithm
algorithm = build_algorithm(args.algo, problem, module_cfg)
print(algorithm)

# generate initial random samples
#X = generate_random_initial_samples(problem, args.n_init_sample)
X = generate_random_initial_samples(problem, args.n_init_sample)
Y = np.array([problem.evaluate_objective(x) for x in X])

print ('read X', X.shape)
print ('read Y', Y.shape)

path = ['./Yuchao_20220511_X.csv', 
        './Yuchao_20220511_Y.csv']
X, Y = load_provided_initial_samples(path)

Y = -Y
print ('read X', X.shape)
print ('read Y', Y.shape)

X0 = X
Y0 = Y

RFclassifier = RF

# optimization
while len(X) < args.n_total_sample:
    
    start = time.time()
    # propose design samples
    X_next = algorithm.optimize(X, Y, X_busy=None, batch_size=4)
    print (X_next)
    # evaluate proposed samples
    Y_next = np.array([problem.evaluate_objective(x) for x in X_next])

    # combine into dataset
    X = np.vstack([X, X_next])
    Y = np.vstack([Y, Y_next])
    print(f'{len(X)}/{args.n_total_sample} complete')
    print (time.time() - start)


10
========== Problem Definition ==========
# name: printing3d_dlp
# n_var: 5
# n_obj: 2
# n_constr: 2


Compiled modules for significant speedup can not be used!
https://pymoo.org/installation.html#installation

To disable this warning:
from pymoo.configuration import Configuration
Configuration.show_compile_hint = False

========== Algorithm Setup ==========
# algorithm: TSEMO
# surrogate: GaussianProcess
# acquisition: ThompsonSampling
# solver: NSGA2
# selection: HypervolumeImprovement

read X (0, 5)
read Y (0,)
read X (40, 5)
read Y (40, 2)


/home/kianoosh/anaconda3/envs/rdkit_env/lib/python3.7/site-packages/sklearn/gaussian_process/kernels.py:437: ConvergenceWarning: The optimal value found for dimension 0 of parameter k1__k2__length_scale is close to the specified upper bound 31.622776601683793. Increasing the bound and calling fit again may find a better value.
  ConvergenceWarning,
/home/kianoosh/anaconda3/envs/rdkit_env/lib/python3.7/site-packages/sklearn/gaussian_process/kernels.py:437: ConvergenceWarning: The optimal value found for dimension 2 of parameter k1__k2__length_scale is close to the specified upper bound 31.622776601683793. Increasing the bound and calling fit again may find a better value.
  ConvergenceWarning,
/home/kianoosh/anaconda3/envs/rdkit_env/lib/python3.7/site-packages/sklearn/gaussian_process/kernels.py:427: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__constant_value is close to the specified lower bound 0.0024787521766663585. Decreasing the bound and calling fit

[[0.34925658 0.23744329 0.00068482 0.10375399 0.16935125]
 [0.23877773 0.13865168 0.11781835 0.13773317 0.12485444]
 [0.19545538 0.23833151 0.37722214 0.10374793 0.08437048]
 [0.33524305 0.33652805 0.18143197 0.05923704 0.08641634]]
ratios A-F [0.35 0.24 0.   0.1  0.17] sum 0.86 Enter objective 0: 10
ratios A-F [0.35 0.24 0.   0.1  0.17] sum 0.86 Enter objective 1: 10
ratios A-F [0.24 0.14 0.12 0.14 0.12] sum 0.76 Enter objective 0: 10
ratios A-F [0.24 0.14 0.12 0.14 0.12] sum 0.76 Enter objective 1: 10
ratios A-F [0.2  0.24 0.38 0.1  0.08] sum 1.0 Enter objective 0: 10
ratios A-F [0.2  0.24 0.38 0.1  0.08] sum 1.0 Enter objective 1: 10
ratios A-F [0.34 0.34 0.18 0.06 0.09] sum 1.0100000000000002 Enter objective 0: 10
ratios A-F [0.34 0.34 0.18 0.06 0.09] sum 1.0100000000000002 Enter objective 1: 10
44/60 complete
420.29695105552673


/home/kianoosh/anaconda3/envs/rdkit_env/lib/python3.7/site-packages/sklearn/gaussian_process/kernels.py:427: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__constant_value is close to the specified lower bound 0.0024787521766663585. Decreasing the bound and calling fit again may find a better value.
  ConvergenceWarning,
/home/kianoosh/anaconda3/envs/rdkit_env/lib/python3.7/site-packages/sklearn/gaussian_process/kernels.py:437: ConvergenceWarning: The optimal value found for dimension 0 of parameter k1__k2__length_scale is close to the specified upper bound 31.622776601683793. Increasing the bound and calling fit again may find a better value.
  ConvergenceWarning,
/home/kianoosh/anaconda3/envs/rdkit_env/lib/python3.7/site-packages/sklearn/gaussian_process/kernels.py:437: ConvergenceWarning: The optimal value found for dimension 2 of parameter k1__k2__length_scale is close to the specified upper bound 31.622776601683793. Increasing the bound and calling fit

[[0.09235881 0.21620807 0.5065185  0.15812866 0.00518809]
 [0.11048818 0.31776932 0.30284973 0.12240714 0.1446845 ]
 [0.14472519 0.15062372 0.02599555 0.16469825 0.09532432]
 [0.09236295 0.19227278 0.48225282 0.15264851 0.0126061 ]]
ratios A-F [0.09 0.22 0.51 0.16 0.01] sum 0.9900000000000001 Enter objective 0: 10
ratios A-F [0.09 0.22 0.51 0.16 0.01] sum 0.9900000000000001 Enter objective 1: 10
ratios A-F [0.11 0.32 0.3  0.12 0.14] sum 0.99 Enter objective 0: 10
ratios A-F [0.11 0.32 0.3  0.12 0.14] sum 0.99 Enter objective 1: 10
ratios A-F [0.14 0.15 0.03 0.16 0.1 ] sum 0.5800000000000001 Enter objective 0: 10
ratios A-F [0.14 0.15 0.03 0.16 0.1 ] sum 0.5800000000000001 Enter objective 1: 10
ratios A-F [0.09 0.19 0.48 0.15 0.01] sum 0.92 Enter objective 0: 10
ratios A-F [0.09 0.19 0.48 0.15 0.01] sum 0.92 Enter objective 1: 10
48/60 complete
1028.9948348999023


/home/kianoosh/anaconda3/envs/rdkit_env/lib/python3.7/site-packages/sklearn/gaussian_process/kernels.py:437: ConvergenceWarning: The optimal value found for dimension 2 of parameter k1__k2__length_scale is close to the specified upper bound 31.622776601683793. Increasing the bound and calling fit again may find a better value.
  ConvergenceWarning,
/home/kianoosh/anaconda3/envs/rdkit_env/lib/python3.7/site-packages/sklearn/gaussian_process/kernels.py:427: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__constant_value is close to the specified lower bound 0.0024787521766663585. Decreasing the bound and calling fit again may find a better value.
  ConvergenceWarning,
/home/kianoosh/anaconda3/envs/rdkit_env/lib/python3.7/site-packages/sklearn/gaussian_process/kernels.py:437: ConvergenceWarning: The optimal value found for dimension 0 of parameter k1__k2__length_scale is close to the specified upper bound 31.622776601683793. Increasing the bound and calling fit

[[0.17622846 0.17589389 0.11349017 0.23305382 0.04795634]
 [0.16214815 0.34030728 0.09845789 0.14607039 0.07181737]
 [0.17675252 0.40336326 0.05592056 0.25160575 0.04908125]
 [0.18462592 0.23935059 0.09765449 0.17081589 0.03819869]]
ratios A-F [0.18 0.18 0.11 0.23 0.05] sum 0.75 Enter objective 0: 10
ratios A-F [0.18 0.18 0.11 0.23 0.05] sum 0.75 Enter objective 1: 10
ratios A-F [0.16 0.34 0.1  0.15 0.07] sum 0.8200000000000001 Enter objective 0: 10
ratios A-F [0.16 0.34 0.1  0.15 0.07] sum 0.8200000000000001 Enter objective 1: 10
ratios A-F [0.18 0.4  0.06 0.25 0.05] sum 0.9400000000000002 Enter objective 0: 10
ratios A-F [0.18 0.4  0.06 0.25 0.05] sum 0.9400000000000002 Enter objective 1: 10
ratios A-F [0.18 0.24 0.1  0.17 0.04] sum 0.7300000000000001 Enter objective 0: 10
ratios A-F [0.18 0.24 0.1  0.17 0.04] sum 0.7300000000000001 Enter objective 1: 10
52/60 complete
359.32087540626526


/home/kianoosh/anaconda3/envs/rdkit_env/lib/python3.7/site-packages/sklearn/gaussian_process/kernels.py:437: ConvergenceWarning: The optimal value found for dimension 2 of parameter k1__k2__length_scale is close to the specified upper bound 31.622776601683793. Increasing the bound and calling fit again may find a better value.
  ConvergenceWarning,
/home/kianoosh/anaconda3/envs/rdkit_env/lib/python3.7/site-packages/sklearn/gaussian_process/kernels.py:427: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__constant_value is close to the specified lower bound 0.0024787521766663585. Decreasing the bound and calling fit again may find a better value.
  ConvergenceWarning,
/home/kianoosh/anaconda3/envs/rdkit_env/lib/python3.7/site-packages/sklearn/gaussian_process/kernels.py:437: ConvergenceWarning: The optimal value found for dimension 0 of parameter k1__k2__length_scale is close to the specified upper bound 31.622776601683793. Increasing the bound and calling fit

KeyboardInterrupt: 

In [ ]:
np.sum(X, axis=1)

In [ ]:
# plot
Y_eval = Y[Y0.shape[0]:, :]
plot_performance_space_diffcolor(Y0=-Y0, Y_eval=-Y_eval)
plot_performance_metric(Y, problem.obj_type)

In [ ]:
Y